# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create!(email: 'jzd.tsai@gmail.com', password: '00000000', password_confirmation: '00000000', admin: true)
Store.create!(name: '香港-發財小館', address: '高雄市鹽埕區七賢三路108號(新樂街口)', tel: '(07)532-4959')
Store.create!(name: '阿英排骨飯', address: '高雄市鹽埕區富野路79-2號(城隍廟邊)', tel: '(07)521-5562')
Store.create!(name: '雞蛋妹小吃店', address: '高雄市鹽埕區新樂街148號', tel: '(07)521-2178')
Store.create!(name: '小西門燉肉飯(鹽埕總店)', address: '高雄市鹽埕區鹽埕街43號', tel: '(07)551-2095')
Store.create!(name: '松江庭', address: '高雄市鹽埕區大仁路148號', tel: '(07)532-7309')
Store.create!(name: '阿梅排骨飯', address: '高雄市鹽埕區新樂街77之1號', tel: '(07)532-1765')
Store.create!(name: '天池芳香冬瓜茶', address: '高雄市鹽埕區新樂街113號', tel: '(07)551-7165')
Store.create!(name: '樺達奶茶', address: '高雄市鹽埕區新樂街99號', tel: '(07)551-2151')
Store.create!(name: '千葉養生素食館', address: '高雄市鹽埕區大義街131號', tel: '(07)551-3665')
Store.create!(name: '鹽埕埔米糕城', address: '高雄市鹽埕區大仁路107號', tel: '(07)533-3168')
Store.create!(name: '妙日式蓋飯', address: '高雄市鹽埕區新樂街188號', tel: '(07)531-3468')
Store.create!(name: '山櫻丼', address: '高雄市前金區允文街52號', tel: '(07)215-0203')
Store.create!(name: '郭家肉粽', address: '高雄市鹽埕區北斗街19號', tel: '(07)551-2747')
Store.create!(name: 'Artisan Cafe 美森咖啡', address: '高雄市前金區仁義街223號', tel: '(07)231-2188')
Store.create!(name: '紅茶阿嬤', address: '高雄市鹽埕區大義街124號騎樓', tel: '(07)561-2527')

Product.create!(store_id: '1', name: '烤鴨腿飯', price: '100')
Product.create!(store_id: '1', name: '招牌三寶飯', price: '90')
Product.create!(store_id: '1', name: '化皮燒肉飯', price: '90')
Product.create!(store_id: '1', name: '油雞腿飯飯', price: '90')
Product.create!(store_id: '1', name: '臘腸拼雞飯', price: '90')
Product.create!(store_id: '1', name: '臘腸拼鴨飯', price: '90')
Product.create!(store_id: '1', name: '叉燒拼鴨飯', price: '80')
Product.create!(store_id: '1', name: '叉燒拼雞飯', price: '80')
Product.create!(store_id: '1', name: '油雞拼鴨飯', price: '80')
Product.create!(store_id: '1', name: '牛肚拼鴨飯', price: '80')
Product.create!(store_id: '1', name: '牛肚拚雞飯', price: '80')
Product.create!(store_id: '1', name: '蜜汁叉燒飯', price: '80')
Product.create!(store_id: '1', name: '脆皮烤鴨飯', price: '80')
Product.create!(store_id: '1', name: '叉燒牛肚飯', price: '80')
Product.create!(store_id: '1', name: '黑椒牛肉飯', price: '110')
Product.create!(store_id: '1', name: '滑蛋牛肉飯', price: '110')
Product.create!(store_id: '1', name: '滑蛋叉燒飯', price: '110')
Product.create!(store_id: '1', name: '滑蛋蝦仁飯', price: '110')
Product.create!(store_id: '1', name: '咖哩牛肉飯', price: '110')
Product.create!(store_id: '1', name: '咖哩雞肉飯', price: '110')
Product.create!(store_id: '1', name: '咖哩牛腩飯', price: '110')
Product.create!(store_id: '1', name: '咖哩海鮮飯', price: '110')
Product.create!(store_id: '1', name: '星洲炒飯', price: '110')
Product.create!(store_id: '1', name: '廣州炒飯', price: '110')
Product.create!(store_id: '1', name: '牛肉炒飯', price: '110')
Product.create!(store_id: '1', name: '蝦仁炒飯', price: '110')
Product.create!(store_id: '1', name: '鹹魚雞粒炒飯', price: '110')
Product.create!(store_id: '1', name: '牛肉燴飯', price: '110')
Product.create!(store_id: '1', name: '牛腩燴飯', price: '110')
Product.create!(store_id: '1', name: '廣州燴飯', price: '110')
Product.create!(store_id: '1', name: '海鮮燴飯', price: '110')
Product.create!(store_id: '1', name: '玉米牛肉燴飯', price: '110')

Product.create!(store_id: '2', name: '雞腿飯', price: '100')
Product.create!(store_id: '2', name: '排骨飯', price: '90')
Product.create!(store_id: '2', name: '白菜魯飯', price: '90')
Product.create!(store_id: '2', name: '魯肉飯', price: '90')
Product.create!(store_id: '2', name: '魚排飯', price: '90')
Product.create!(store_id: '2', name: '筍干扣肉飯', price: '90')

Product.create!(store_id: '3', name: '肉絲飯炒飯', price: '70')
Product.create!(store_id: '3', name: '培根蛋炒飯', price: '75')
Product.create!(store_id: '3', name: '蝦仁蛋炒飯', price: '75')
Product.create!(store_id: '3', name: '什錦蛋炒飯', price: '75')
Product.create!(store_id: '3', name: '麻油雞絲蛋炒飯', price: '75')
Product.create!(store_id: '3', name: '黑胡椒豬柳炒飯', price: '75')
Product.create!(store_id: '3', name: '德國香腸蛋炒飯', price: '75')
Product.create!(store_id: '3', name: '沙茶豬肉燴飯', price: '70')

Product.create!(store_id: '4', name: '蛋黃瓜仔肉飯', price: '65')
Product.create!(store_id: '4', name: '燉肉飯(梅干扣肉)', price: '75')
Product.create!(store_id: '4', name: '筍絲蹄膀飯', price: '75')
Product.create!(store_id: '4', name: '香菇苦瓜肉飯', price: '70')
Product.create!(store_id: '4', name: '扁魚白菜飯', price: '70')
Product.create!(store_id: '4', name: '火燒排骨飯', price: '75')
Product.create!(store_id: '4', name: '白菜燉牛肉飯', price: '85')
Product.create!(store_id: '4', name: '虱目魚肚飯(無刺)', price: '90')
Product.create!(store_id: '4', name: '香酥雞排飯', price: '75')
Product.create!(store_id: '4', name: '粉炸豬排飯', price: '75')
Product.create!(store_id: '4', name: '紅糟炸排骨飯', price: '75')
Product.create!(store_id: '4', name: '塔塔雞柳飯', price: '75')
Product.create!(store_id: '4', name: '粉炸魚排飯', price: '75')
Product.create!(store_id: '4', name: '酥炸雞腿飯', price: '85')
Product.create!(store_id: '4', name: '日式鱈魚飯', price: '90')

Product.create!(store_id: '5', name: '鰻魚便當', price: '220')
Product.create!(store_id: '5', name: '特製鮭魚炒飯便當', price: '150')
Product.create!(store_id: '5', name: '特製壽司便當B', price: '150')
Product.create!(store_id: '5', name: '特製蛋包飯便當', price: '150')
Product.create!(store_id: '5', name: '天丼便當', price: '150')
Product.create!(store_id: '5', name: '特製便當', price: '150')
Product.create!(store_id: '5', name: '豬排蓋飯便當', price: '130')
Product.create!(store_id: '5', name: '鯖魚便當', price: '100')
Product.create!(store_id: '5', name: '日式便當', price: '100')
Product.create!(store_id: '5', name: '排骨便當', price: '80')
Product.create!(store_id: '5', name: '雞腿便當', price: '90')
Product.create!(store_id: '5', name: '鱈魚便當', price: '85')
Product.create!(store_id: '5', name: '壽司便當', price: '85')
Product.create!(store_id: '5', name: '蛋包飯便當', price: '85')
Product.create!(store_id: '5', name: '雞腿飯便當', price: '65')
Product.create!(store_id: '5', name: '魚排便當', price: '65')
Product.create!(store_id: '5', name: '紫菜豆皮壽司便當', price: '65')
Product.create!(store_id: '5', name: '排骨飯便當', price: '65')
Product.create!(store_id: '5', name: '三杯雞便當', price: '65')
Product.create!(store_id: '5', name: '宮保雞丁便當', price: '90')
Product.create!(store_id: '5', name: '綜合便當', price: '65')
Product.create!(store_id: '5', name: '魯排骨飯', price: '99')
Product.create!(store_id: '5', name: '照燒雞飯', price: '65')
Product.create!(store_id: '5', name: '果蔬沙拉/和風醬', price: '90')

Product.create!(store_id: '6', name: '排骨飯', price: '60')
Product.create!(store_id: '6', name: '雞腿飯', price: '80')
Product.create!(store_id: '6', name: '魚排飯', price: '70')
Product.create!(store_id: '6', name: '肉絲蛋炒飯', price: '65')
Product.create!(store_id: '6', name: '蝦仁蛋炒飯', price: '65')
Product.create!(store_id: '6', name: '香腸蛋炒飯', price: '65')
Product.create!(store_id: '6', name: '什錦蛋炒飯', price: '65')
Product.create!(store_id: '6', name: '原味蛋炒飯', price: '45')
Product.create!(store_id: '6', name: '紅飯', price: '50')
Product.create!(store_id: '6', name: '雞肉飯', price: '40')
Product.create!(store_id: '6', name: '滷肉飯', price: '40')

Product.create!(store_id: '7', name: '冬瓜茶(大杯)', price: '35')
Product.create!(store_id: '7', name: '冬瓜茶(瓶裝)', price: '60')
Product.create!(store_id: '7', name: '冬瓜牛奶(大杯)', price: '40')
Product.create!(store_id: '7', name: '冬瓜牛奶(瓶裝)', price: '80')
Product.create!(store_id: '7', name: '冬瓜烏龍(大杯)', price: '30')
Product.create!(store_id: '7', name: '冬瓜烏龍(瓶裝)', price: '55')
Product.create!(store_id: '7', name: '冬瓜綠茶(大杯)', price: '30')
Product.create!(store_id: '7', name: '冬瓜綠茶(瓶裝)', price: '55')
Product.create!(store_id: '7', name: '冬瓜紅茶(大杯)', price: '30')
Product.create!(store_id: '7', name: '冬瓜紅茶(瓶裝)', price: '55')
Product.create!(store_id: '7', name: '冬瓜檸檬(大杯)', price: '40')
Product.create!(store_id: '7', name: '冬瓜檸檬(瓶裝)', price: '80')
Product.create!(store_id: '7', name: '紅茶(大杯)', price: '20')
Product.create!(store_id: '7', name: '紅茶(瓶裝)', price: '45')
Product.create!(store_id: '7', name: '綠茶(大杯)', price: '20')
Product.create!(store_id: '7', name: '綠茶(瓶裝)', price: '45')
Product.create!(store_id: '7', name: '烏龍茶(大杯)', price: '20')
Product.create!(store_id: '7', name: '烏龍茶(瓶裝)', price: '45')
Product.create!(store_id: '7', name: '檸檬紅茶(大杯)', price: '30')
Product.create!(store_id: '7', name: '檸檬紅茶(瓶裝)', price: '45')
Product.create!(store_id: '7', name: '紅茶牛奶(大杯)', price: '35')
Product.create!(store_id: '7', name: '紅茶牛奶(瓶裝)', price: '65')

Product.create!(store_id: '8', name: '樺達奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '樺達奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '美容奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '美容奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '益壽奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '益壽奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '普洱奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '普洱奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '綠奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '綠奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '綠茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '綠茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '紅茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '紅茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '紅龍茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '紅龍茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '紅龍奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '紅龍奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '梅子綠(大杯)', price: '40')
Product.create!(store_id: '8', name: '梅子綠(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '檸檬紅茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '檸檬紅茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '桂花烏龍(大杯)', price: '40')
Product.create!(store_id: '8', name: '桂花烏龍(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '紅龍奶茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '紅龍奶茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '烏梅綠茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '烏梅綠茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '烏梅紅茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '烏梅紅茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '烏梅普洱(大杯)', price: '40')
Product.create!(store_id: '8', name: '烏梅普洱(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '早茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '早茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '午茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '午茶(瓶裝)', price: '80')
Product.create!(store_id: '8', name: '晚茶(大杯)', price: '40')
Product.create!(store_id: '8', name: '晚茶(瓶裝)', price: '80')

Product.create!(store_id: '9', name: '招牌便當(486卡)', price: '55')
Product.create!(store_id: '9', name: '五穀便當(600卡)', price: '55')
Product.create!(store_id: '9', name: '水餃便當(415卡)', price: '55')
Product.create!(store_id: '9', name: '碗粿便當(392卡)', price: '55')
Product.create!(store_id: '9', name: '壽司便當(570卡)', price: '65')
Product.create!(store_id: '9', name: '炒麵便當(565卡)', price: '65')
Product.create!(store_id: '9', name: '炒米粉便當(542卡)', price: '65')
Product.create!(store_id: '9', name: '米糕便當(497卡)', price: '65')

Product.create!(store_id: '10', name: '米糕', price: '30')
Product.create!(store_id: '10', name: '肉燥飯', price: '25')

Product.create!(store_id: '11', name: '滑蛋肉末蓋飯', price: '65')
Product.create!(store_id: '11', name: '杏鮑菇蓋飯', price: '75')
Product.create!(store_id: '11', name: '雪花豬肉蓋飯', price: '85')
Product.create!(store_id: '11', name: '雪花牛肉蓋飯', price: '95')
Product.create!(store_id: '11', name: '親子丼(雞肉)蓋飯', price: '95')
Product.create!(store_id: '11', name: '豬排蓋飯', price: '95')
Product.create!(store_id: '11', name: '起司豬排蓋飯', price: '105')
Product.create!(store_id: '11', name: '咖哩飯', price: '95')
Product.create!(store_id: '11', name: '咖哩豬排飯', price: '105')

Product.create!(store_id: '12', name: '日式海鮮丼', price: '170')
Product.create!(store_id: '12', name: '鮭魚親子丼', price: '200')
Product.create!(store_id: '12', name: '月見鐵火丼', price: '200')
Product.create!(store_id: '12', name: '鮮魚三色丼', price: '200')
Product.create!(store_id: '12', name: '北海道甜蝦丼', price: '270')
Product.create!(store_id: '12', name: '星鰻魚丼', price: '300')
Product.create!(store_id: '12', name: '海景散壽司', price: '330')
Product.create!(store_id: '12', name: '唐揚雞', price: '130')
Product.create!(store_id: '12', name: '日本鯖魚', price: '130')
Product.create!(store_id: '12', name: '厚切豬排', price: '130')
Product.create!(store_id: '12', name: '照燒雞腿', price: '170')
Product.create!(store_id: '12', name: '鹽麴五花肉', price: '200')
Product.create!(store_id: '12', name: '北海道花魚', price: '250')

Product.create!(store_id: '13', name: '肉粽', price: '30')
Product.create!(store_id: '13', name: '碗粿', price: '30')

Product.create!(store_id: '14', name: 'Espresso(熱)', price: '100')
Product.create!(store_id: '14', name: '美式咖啡(熱)(冰)', price: '100')
Product.create!(store_id: '14', name: '拿鐵咖啡(熱)(冰)', price: '120')
Product.create!(store_id: '14', name: '卡布奇諾(熱)', price: '120')
Product.create!(store_id: '14', name: '榛果拿鐵(熱)(冰)', price: '140')
Product.create!(store_id: '14', name: '香草拿鐵(熱)(冰)', price: '140')
Product.create!(store_id: '14', name: '太妃糖拿鐵(熱)(冰)', price: '140')
Product.create!(store_id: '14', name: '焦糖瑪奇朵(熱)(冰)', price: '150')
Product.create!(store_id: '14', name: '抹茶拿鐵(熱)(冰)', price: '160')
Product.create!(store_id: '14', name: '法芙娜可可摩卡奇諾(熱)(冰)', price: '160')

Product.create!(store_id: '15', name: '紅茶', price: '20')
Product.create!(store_id: '15', name: '紅茶豆漿', price: '25')
Product.create!(store_id: '15', name: '紅茶牛奶', price: '30')
Product.create!(store_id: '15', name: '青草茶', price: '25')
Product.create!(store_id: '15', name: '綠茶', price: '20')
Product.create!(store_id: '15', name: '紅茶', price: '20')
Product.create!(store_id: '15', name: '綠豆露', price: '25')
Product.create!(store_id: '15', name: '檸檬汁', price: '40')
Product.create!(store_id: '15', name: '百香果', price: '40')

